backend:
  name: git-gateway
  branch: main
  
local_backend: true 

media_folder: "assets/img" 
public_folder: "/assets/img"

collections:
  - name: "site_content"
    label: "Contenido General"
    files:
      - file: "index.html"
        label: "Página de Inicio"
        name: "home"
        fields:
          - {label: "Mensaje Principal (H1)", name: "hero_title", widget: "string", default: "Especialistas en Aire Acondicionado Automotriz y Mantenimiento Integral."}
          - {label: "Subtítulo de Inicio", name: "hero_subtitle", widget: "text", default: "Precisión, experiencia y compromiso real en cada unidad. Más de 15 años cuidando tu inversión."}
          - {label: "Teléfono WhatsApp (Completo, con +52)", name: "whatsapp_number", widget: "string", default: "+521234567890"}
